### ISSUE TITLE
Compressed video cannot be sent via Whatsapp

### ISSUE THREAD

**Issue by riskikukuh** [AbedElazizShe/LightCompressor#60]
- Device name
Realme 5 Pro
- Android version
Android 10
- Library Version
`0.8.0`

**Description issue**
Compressed video cannot be sent via whatsapp, and show dialog "Can't send this video. Choose a different video and try again". Preset compress : VideoQuality.VERY_HIGH, isMinBitRateEnabled = true, keepOriginalResolution = true

Screenshot error
![1](https://user-images.githubusercontent.com/37315929/110354051-54a63700-806a-11eb-94b0-dd93a7789da4.jpeg)

**Comment by riskikukuh** [comment]
@AbedElazizShe Can you please have a look on the issue

**Comment by AbedElazizShe** [comment]
@riskikukuh thank you for opening the issue and all the provided details. I will look into it and get back to you soon, I am a bit busy these days that it may take me a week or so before releasing a new version. Sorry for that. Just a question, does it happen in other devices or just the provided one? As I am using BrowserStack for testing and that model does not exist.

**Comment by riskikukuh** [comment]
@AbedElazizShe it also happened in Samsung ( idk specific device name ) android 8 and Xiaomi with Custom Rom android 11. 

I also test other library with base from Telegram like https://github.com/lalongooo/video-compressor and it work for compressing and send compressed video to Whatsapp. Maybe that can help.

Thank you for your response

**Comment by AbedElazizShe** [comment]
@riskikukuh thank you, I have fixed the issue and I will release a new version shortly.

**Comment by AbedElazizShe** [comment]
Issue fixed in version 0.8.1. Please let me know if you still have the issue. You can close the task if the problem is solved.

**Comment by riskikukuh** [comment]
@AbedElazizShe thank you for the update, but i still facing the issue. Ii think this issue happened because whatsapp add limitation like bitrate or something

**Comment by AbedElazizShe** [comment]
@riskikukuh could ypu please confirm you're using the lastet version? I fixed the issue and it does not happen again in the last version. If it keeps happening, let me know the list of devices you used for testing. thank you.

**Comment by jaySC123** [comment]
Hi @AbedElazizShe, i'm using v0.9.0 of this library and can confirm that this issue is still happening. i'm sending compressed videos to whatsapp via twilio, and when the videos get downloaded it gives a similar dialog. if i try to upload the same compressed video via whatsapp, the dialog in @riskikukuh 's screenshot shows
